app = "p2p-agents"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  P2P_PORT = "8000"
  P2P_NODE_PATH = "/app/node/p2p-node"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 8000
    handlers = ["proxy_proto"]

[metrics]
  port = 9091
  path = "/metrics"

[processes]
  app = "pnpm run agent" 